{% set name = "galaxy_bulk_upload_from_server" %}
{% set version = "0.0.2" %}
{% set sha256 = "5f280eaaf348c415990f509bf70a3b6fb7096c386bd5dc718b30b3065dcdc74c" %}
{% set author = "pvanheus" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bioblend
    - pyyaml
    - tqdm

test:
  commands:
    - bulk_upload_to_library.py --help

about:
  home: http://github.com/{{ author }}/{{ name }}
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Bulk upload FASTQ files from server to Galaxy'
  description: |
    using the Galaxy API, upload files to a Galaxy server
